SELECT TOP (1000) [InvoiceLineId]
      ,[InvoiceId]
      ,[InvoiceDate]
      ,[BillingCountry]
      ,[CustomerId]
      ,[CustomerName]
      ,[TrackId]
      ,[TrackName]
      ,[ArtistId]
      ,[Artist]
      ,[GenreId]
      ,[Genre]
      ,[UnitPrice]
      ,[Quantity]
      ,[Revenue]
  FROM [Chinook].[dbo].[vw_Sales]
